### ISSUE TITLE
Error with loading data

### ISSUE THREAD

**Issue by b-jufre** [ruby-processing/JRubyArt#14]
### Environment

k9 setup check:
`RubyArt version 1.0.7
    PROCESSING_ROOT = /Applications/Processing.app/Contents/Java
    JRUBY = false
    jruby-complete installed = true`

jruby -v
`jruby 9.1.0.0 (2.3.0) 2016-05-02 a633c63 Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [darwin-x86_64]`

java -version
`java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)`

k9 --version:
`JRubyArt version 1.0.7`

### Expected Behavior

The sketch should show the image with the histogram:
       k9_samples/processing_app/topics/image_processing/histogram.rb

(But it happens with any sketch that requires depends on archives inside a data folder).

### Actual Behavior

Every time I try to run any sketch file with stuff loading from the data folder a get this kind of error:

`CompilerOracle: dontinline org/jruby/runtime/invokedynamic/InvokeDynamicSupport.invocationFallback
The file "frontier.jpg" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
Java::JavaLang::NullPointerException
	processing.core.PGraphics.image(processing/core/PGraphics.java:3765)
	processing.core.PApplet.image(processing/core/PApplet.java:12116)
	java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:423)
	org.jruby.javasupport.JavaMethod.tryProxyInvocation(org/jruby/javasupport/JavaMethod.java:613)
	org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:287)
	RUBY.setup(samples/processing_app/topics/image_processing/histogram.rb:17)
	org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:229)
	org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:212)
	processing.core.PApplet.handleDraw(processing/core/PApplet.java:2378)
	processing.awt.PSurfaceAWT$12.callDraw(processing/awt/PSurfaceAWT.java:1527)
	processing.core.PSurfaceNone$AnimationThread.run(processing/core/PSurfaceNone.java:316)`

**Comment by monkstone** [comment]
OK if I'm right you are using jruby-complete (because config JRUBY = false) so you don't need the `--nojruby` flag. So your problem should just be the data path. You could try:-

1. Absolute data path (should be bombproof)
2. Wrap the file `data_path('frontier.jpg')`

But it should just work, have you tested the example sketches eg [background_image.rb](https://github.com/ruby-processing/samples4ruby-processing3/blob/master/processing_app/basics/image/background_image.rb), that way I can check without needing your code.
eg

**Comment by b-jufre** [comment]
I ran it without the --nojruby flag and still doesn't work, and I've just tried to run the background_image.rb and it does fail as well.

Let me see if wrapping the file with `data_path`works.

**Comment by monkstone** [comment]
Having read line 7531 and onwards of the PApplet code:-
https://github.com/processing/processing/blob/master/core/src/processing/core/PApplet.java
or thereabouts I'm not sure data_path will do any better, but you are in better place to test than me you could possibly use your ruby knowledge to use the absolute data path, there may even be a permissions thing going on (works fine on linux).

**Comment by b-jufre** [comment]
Funny enough using `File.absolute_path "data/milan_rubbish.jpg"` it works like a charm. Nonetheless having to use this method every time it gets annoying after a while.

Whenever I try to print out the `data_path` of the current sketch it gives me `/Applications/data/milan_rubbish.jpg` (in this particular case with `background_image.rb

**Comment by monkstone** [comment]
The `data_path` wrapper from what I read should do exactly the same thing from the java side, just in case there's a namespace clash you could try `dataPath` (although logically it does not make sense, works on linux either way).

**Comment by b-jufre** [comment]
Yeah I'm just looking into it, I'll do a PR when I have something. Thank you for your help man!

**Comment by b-jufre** [comment]
BTW! I just tried the `load_display_image.rb` wrapped and I still have problems.

**Comment by b-jufre** [comment]
@monkstone Solved, the last build processing-3.1 works like a charm, I don't know why :) Thank you for your time and work!!

**Comment by b-jufre** [comment]
Sorry man, it fails again... :'(

**Comment by monkstone** [comment]
There may be a problem that not all the images get loaded before the shaders, here is something to try, and or experiment with:-
https://gist.github.com/monkstone/b53549b335b13f97dbc28736f704b61f
If simpler shader sketches work it is most likely the problem.

**Comment by b-jufre** [comment]
It's weird, `File.absolute_path` it's an absolute bulletproof aproach, but without it and prefixing the path with `data/file-to-load` works...

**Comment by monkstone** [comment]
1. It might be interesting to test where data gets stored as on 'save_frame' , and or 'save' 
2. And how you get on with the `advanced_data/counting_words` sketch where I use `data_path` (java) in combination with `File.read` (ruby) to load a text file.

**Comment by b-jufre** [comment]
It saves the exports on `/Applications/` not even a "data" folder:
<img width="1440" alt="captura de pantalla 2016-05-12 a las 16 00 28" src="https://cloud.githubusercontent.com/assets/17750928/15217214/c5fb8130-185a-11e6-95c2-574af7f5e8a3.png">


Answering your second question first, this is exactly what I get:
<img width="1440" alt="captura de pantalla 2016-05-12 a las 15 57 05" src="https://cloud.githubusercontent.com/assets/17750928/15217087/3cb9f028-185a-11e6-9057-bbf82b638223.png">

**Comment by monkstone** [comment]
Thanks for testing, I can't believe that happens with vanilla processing, the only thing we do differently is not to nest sketches in an eponymous named folder. However on linux the pre-processed sketch java file ends up in the /tmp folder along with compiled class, so they would definitely need to refer to an absolute data-path when data path is say on linux remains at /home/tux/sketchbook3/SomeSketch/data/data.txt like dowm a completely different path and not relative at all.

**Comment by b-jufre** [comment]
Would you mind if I fork your repo so I can go and take a look and try to figure it out this weekend? I don't wanna bother you with this bug, if you're busy. I'd do a PR if I'm able to solve it.

I'll look into it.

Thanks a lot for your help man!

**Comment by monkstone** [comment]
Ideally fork processing-3.1 branch, but it shouldn't matter (you'll need maven though).

**Comment by b-jufre** [comment]
I've been reading the source code, and playing around with some sketches logging out some variables and constants:

`"SKETCH_ROOT: ."
"File.absolute_path SKETCH_ROOT: /Users/bjufre/Documents/processing/jruby/autism"
"SKETCH_PATH: autism.rb"
"self.sketchPath: /Applications"
"self.dataPath("test-file.jpg"): /Applications/data/test-file.jpg"`

As I understand the problem is that the Processing::App, as I understand the one that inherits from PApplet doesn't set the path correctly.

**Comment by b-jufre** [comment]
The python mode had a similar bug and they fixed it.
Maybe this could help somehow: https://github.com/jdf/Processing.py-Bugs/issues/138

**Comment by monkstone** [comment]
@b-jufre The python issue is probably different, but it got me to re-read JRubyArt and vanilla PApplet code which was instructive.  I got rid off the non-implemented mac-icon (legacy from ruby-processing), which might have served to confuse things on the mac. I have also exposed the `private String sketchPath` variable as readable (using `field_reader`, if needed we could use `field_accessor` to be able to set the variable, but I would prefer not to). I have even added a minitest script that is guaranteed to fail because expects the sketch output of 'ok' when the actual output is the sketchPath (and believe or not this correctly reported on linux).  All mods on processing-3.1 branch.

**Comment by b-jufre** [comment]
It gives an error due to the fact that sketchPath it's a private variable from the PApplet. You get an `illegal access`exception.

`Java::OrgJrubyExceptions::RaiseException`
`(TypeError) illegal access`
	`org.jruby.javasupport.JavaField.value(org/jruby/javasupport/JavaField.java:130)`
	`RUBY.sketch_path(/Users/bjufre/.rvm/gems/jruby-9.1.0.0/gems/jruby_art`
`1.0.8/lib/jruby_art/helper_methods.rb:141)`

**Comment by monkstone** [comment]
Is that with the modded version https://github.com/ruby-processing/JRubyArt/blob/processing-3.1/lib/jruby_art/app.rb, because that is how I access `surface`

**Comment by monkstone** [comment]
Interestingly if I remove the sketchPath helper method (only required because vanilla processing _inconveniently_ uses same name for method and variable) most many shader sketches will run except say conway which prefixes shader name with `data` (because then sketchPath gets called, and the variable does not take arguments).

**Comment by monkstone** [comment]
@b-jufre I've now re-implemented sketch_path method directly in app with option of being a getter and setter, seems to work for me conway sketch works with and without data prefix. Delay in writing up due to making pizza (from first principles ).

**Comment by b-jufre** [comment]
You need to access the underlying java.Field in order to call `set_value`. But I get "rescued" with the `Did not work`.

`def sketch_path(spath = nil)`
      `return java_class.declared_field('sketchPath') unless spath`
      `begin`
        `field = java_class.declared_field('sketchPath')`
        `field.set_value(java_self, spath || SKETCH_ROOT)`
      `rescue TypeError`
        `fail 'Did not work'`
      `end`
    `end`

**Comment by monkstone** [comment]
Yeah I know and working on it to test I think need to call sketch_path in settings, slight delay to have meal.

**Comment by b-jufre** [comment]
No worries man! I'm at work haha and I'm going between editors switching :P

**Comment by b-jufre** [comment]
I've tried in settings, and still give me an error, and I changed 

```ruby
  return java_class.declared_field('sketchPath') unless spath```

to:

```ruby

**Comment by b-jufre** [comment]
Nonetheless, the changed made "data/" to get prefixed to whatever you pass to `data_path`. But still getting back the incorrect path `/Application/data`. We're getting closer...

**Comment by monkstone** [comment]
b-jufre I have simplified everything in the latest change, and seems the right thing to do. May not fix mac issue which might benefit from exploring ThinkDifferent.java (but that brings us into realms of signing jars etc). I don't know why/how jdf exposed `sketchPath` it is a public method (well two really a getter and a setter), so should have already been available to processing.py, we probably should not try to access the private variable.
Anyway one consequence of  this change is that the the data prefix must go, use either just name or absolute path for data files.

**Comment by monkstone** [comment]
It is entirely possible that the source of the problems is presence of a Mac  *.app in sketch folder see this [gist ](https://gist.github.com/monkstone/e817fd20ae2d5fa8025d094725ab4dbf), in presence of *.app (ThinkDifferent crap) Mac expects data in a F*k Apple different  location ie not local folder to sketch.

**Comment by b-jufre** [comment]
I had a python mode app inside it, but I remove it and I still get the same problem. I've also tried copying the "load_display_image.rb" example to a separate folder with the same name, because usually processing needs the file and the folder to be named the same way, but still got the same error. I'm reading the full fucking source code for processing to see and figure it out ahahha Mac is good for some things, but for others, sucks...

**Comment by monkstone** [comment]
@b-jufre for the benefit of casual Mac users I'm going to close  this issue and re-open issue with simpler story ie just including the proposed workaround.
