### ISSUE TITLE
Issue with --watch

### ISSUE THREAD

**Issue by monkstone** [ruby-processing/JRubyArt#21]
@tyfkda reported an issue with --watch latest version of gem to try:-
[gem.zip](https://github.com/ruby-processing/JRubyArt/files/393819/gem.zip)

**Comment by tyfkda** [comment]
Solved, I misconfigured ~/.jruby_art/config.yml to use jruby, although I haven't installed it.

**Comment by monkstone** [comment]
@tyfkda I've never seen that error before when jruby isn't installed, anway thanks for report.
