### ISSUE TITLE
Installation Issue: Problem running sketches

### ISSUE THREAD

**Issue by acgillette** [ruby-processing/JRubyArt#28]
### Other

eg installation issue (just use this header and explain the problem as best you can)

I just recently installed jruby_art following the macOS instructions. However when I try and run an example I get an error message: 

```
Running ./raining.rb...quit to run next sample
LoadError: load error: /usr/local/lib/ruby/gems/2.4.0/gems/jruby_art-1.2.9/lib/jruby_art/app -- java.lang.NoClassDefFoundError: processing/core/PApplet
           require at org/jruby/RubyKernel.java:961
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
            <main> at /usr/local/lib/ruby/gems/2.4.0/gems/jruby_art-1.2.9/lib/jruby_art/runners/base.rb:6
           require at org/jruby/RubyKernel.java:961
            (root) at uri:classloader:/jruby/kernel/kernel.rb:1
            <main> at /usr/local/lib/ruby/gems/2.4.0/gems/jruby_art-1.2.9/lib/jruby_art/runners/run.rb:2
```
Any idea what is causing the issue?

**Comment by monkstone** [comment]
Yes the problem is that your config file ~/.jruby_art/config.yml is not pointing to the vanilla processing folder.
see http://ruby-processing.github.io/JRubyArt/mac_start/. Assuming you've installed vanilla processing with `HomeBrew` you need to adjust the `PROCESSING_ROOT: /Applications/Processing.app/Contents/Java` to `/Users/acgillette/Application/Processing.app/Contents/Java` or similar for your system.

If you have not installed vanilla processing `propane` is a configuration free alternative that doesn't need a vanilla processing install.

**Comment by acgillette** [comment]
I thought I had pointed it correctly? My Processing app is in the app folder and this is how my config file is configured: 

```
PROCESSING_ROOT: "/Users/acgillette/Applications/Processing.app/Contents/Java"
JRUBY: false
sketchbook_path: "/Users/acgillette/Documents/Processing"
template: bare
MAX_WATCH: 32
sketch_title: JRubyArt Static Sketch
width: 600
height: 600
```

**Comment by monkstone** [comment]
Head scratching now. Try removing quotes (they should not be needed with yaml).

**Comment by monkstone** [comment]
Just confirmed that on my linux box that it is still working without a `jruby` install (I don't do full matrix testing every time). Might be worth checking java? needs to be jdk8 (_vanilla processing comes with its own jdk but we can't/don't use that_), both open-jdk and Oracle jdk work on linux, but it is probably safer to use Oracle jdk on MacOS (and doesn't need a separate install for javafx).

**Comment by monkstone** [comment]
I can confirm that on my system If I point to wrong folder this the  message I get:-
java.lang.NoClassDefFoundError: processing/core/PApplet
           require at org/jruby/RubyKernel.java:961
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
            <main> at /home/tux/.gem/ruby/2.4.0/gems/jruby_art-1.2.9/lib/jruby_art/runners/base.rb:6
           require at org/jruby/RubyKernel.java:961
            (root) at uri:classloader:/jruby/kernel/kernel.rb:1
            <main> at /home/tux/.gem/ruby/2.4.0/gems/jruby_art-1.2.9/lib/jruby_art/runners/run.rb:2

**Comment by acgillette** [comment]
I am pretty new to Ruby and gems, where would I edit the installed gem? And thanks for the help :) I'm still pretty new to programming so I'm not so adept at understanding and handling errors.

**Comment by acgillette** [comment]
The path to the libraries is the exact same as the one provided so I'm not sure if that is the issue. Should I copy the full path from Users and see if that works?

**Comment by monkstone** [comment]
From your error listing the file to edit is:-
/usr/local/lib/ruby/gems/2.4.0/gems/jruby_art-1.2.9/lib/jruby_art/app.rb

But first recheck '~/.jruby_art/config.yml'

```bash
less '~/.jruby_art/config.yml'
```
and 

```bash
ls /Users/acgillette/Applications/Processing.app/Contents/Java
```

If the last one contains 'core.jar' etc then there is still a configuration problem, but you could get round it

```ruby
Dir["/Users/acgillette/Applications/Processing.app/Contents/Java/\*.jar"].each do |jar|
```

**Comment by acgillette** [comment]
Ok! I changed the file in atom, how do I reinstall the changes?

**Comment by monkstone** [comment]
just try it should run

**Comment by acgillette** [comment]
Still getting the same error. I had unpacked it and changed it through there so if I wasn't supposed to do it that way that could be it, but otherwise I seem to be getting the same error.

**Comment by monkstone** [comment]
If you need to reinstall gem from rubygems just `gem uninstall jruby_art` followed by `gem install jruby_art`
then `k9 --install`

**Comment by acgillette** [comment]
It worked! Thanks so much!

**Comment by monkstone** [comment]
@acgillette Good happy coding, if you run into problems loading gems for jruby_art it is much simpler if you install jruby on your system rather than use jruby-complete (but it often worked for me but I did specify GEM_HOME and GEM_PATH on my system).
