### ISSUE TITLE
Wrong Ruby Version

### ISSUE THREAD

**Issue by nach00** [ruby-processing/JRubyArt#40]
### Environment
processing 3.3.6
jruby 9.1.13
java oracle-java8-installer
jrubyart 1.4.5
ubuntu

### Expected Behavior

k9 --run jwishy.rb

### Actual Behavior

/home/u/.rvm/gems/ruby-2.4.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:5:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
	from /home/u/.rvm/gems/ruby-2.4.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:5:in `<class:Noexec>'
	from /home/u/.rvm/gems/ruby-2.4.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:3:in `<top (required)>'
	from /home/u/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/u/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/u/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/u/.rvm/gems/ruby-2.4.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	from /home/u/.rvm/gems/ruby-2.4.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:50:in `block in run'
	from /home/u/.rvm/gems/ruby-2.4.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `each'
	from /home/u/.rvm/gems/ruby-2.4.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `run'
	from /home/u/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:10:in `<main>'

### Other

This has been giving me a headache for over 4 hours... I can't figure out what I'm doing wrong. I've goen through every guide at least 5 times and followed every instruction exactly...

**Comment by monkstone** [comment]
I personally avoid using rvm, and it should not be needed, as what is is required is `jruby` on path, as a failsafe try `jruby -S k9 --run jwishy.rb` alternatively if you are using `jruby-complete` it shouldn't matter what version of `ruby` you use. However your `~/.jruby_art/config.yml` should be amended:-
`JRUBY: false`. To get jruby on your path on ubuntu (or any debian) I recommend using update-alternatives:-
http://ruby-processing.github.io/JRubyArt/linux_started/

**Comment by monkstone** [comment]
See also
https://github.com/rvm/rvm/issues/4223
Best to install jruby another way I would say...

**Comment by nach00** [comment]
oh wow, thanks. All I needed to do was set `JRUBY: false` and it worked. Thanks for the quick response.
