### ISSUE TITLE
for windows JRubyArt 

### ISSUE THREAD

**Issue by DimitryBur** [ruby-processing/JRubyArt#41]
Windows 7
java version 1.8.0_91
JRubyArt version 1.4.6
jruby version 9.1.15.0(2.3.3)

### Actual Behavior

By doing "k9 --run test.rb"
 > LoadError: load error: C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/jruby_art-1.4.6/lib/jruby_art/app --java.lang.NoClassDefFoundError: processing/core/PApplet

>  require at org/jruby/RubyKernel.java:955

>require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
><main> at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/jruby_art-1.4.6/lib/jruby_art/runners/base.rb:6

**Comment by monkstone** [comment]
Suggests you haven't got ~/.jruby_art/config.yml set correctly:- You need to find where processing is installed and point to that folder see http://ruby-processing.github.io/JRubyArt/windows_start/

**Comment by DimitryBur** [comment]
Hello,  ~/.jruby_art/config.yml set correctly, 
Very important detail for Windows: for correctly patch PROCESSING_ROOT use " \ ".
Thank yoy, all to work.

**Comment by monkstone** [comment]
@DimitryBur I'm not a Windows user, if you have suggestions you can add them to wiki thanks.
