### ISSUE TITLE
Currently Export to App is Not Supported

### ISSUE THREAD

**Issue by monkstone** [ruby-processing/JRubyArt#8]
The original ruby-processing supported export of OS specific applications, it would seem saner to create a cross-platform exporter using say [warbler](https://github.com/jruby/warbler).
@stevekinney, @fluxusfrequency, @poqudrof  have you any experience?

**Comment by poqudrof** [comment]
Nope I don't know this, it looks really nice though.

**Comment by dfl** [comment]
I'm trying to package a basic sketch (jwishy.rb) with warbler as an example. will let you know if/when I get it working.

**Comment by monkstone** [comment]
@dfl I guess the ideal would be use maven to serve up jar artifacts (well specifically processing), just found some kind person has made processing-3.0.2 artefacts available from maven (probably @poqudrof ) I can't see Ben Fry doing it.

**Comment by poqudrof** [comment]
Yes I made it available, I was away for a while sorry for the delay for the jars ! 
I did not see the 3.1, I will make it today so it might be available tomorrow.

**Comment by monkstone** [comment]
@poqudrof @dfl this will likely impact application export of JRubyArt / propane on macOS although the jruby guys might find a way round it https://github.com/processing/processing/issues/4705

**Comment by monkstone** [comment]
@poqudrof @dfl we should follow progress in this shoes4 issue https://github.com/shoes/shoes4/issues/1415, they have a more compelling need to solve the problem.

**Comment by monkstone** [comment]
Seem irrelevant now.
