### ISSUE TITLE
Sketches not starting with Processing b3

### ISSUE THREAD

**Issue by poqudrof** [ruby-processing/JRubyArt#9]
Hello, 

I recently moved to Processing 3, and it seems that JRubyArt is not working on my machine. 

Here is the message : 

```bash
k9 run jwishy.rb 
LoadError: load error: /home/jiii/.rvm/gems/jruby-9.0.0.0.pre1/gems/jruby_art-0.4.2/lib/jruby_art/app -- java.lang.NoClassDefFoundError: processing/core/PApplet
           require at org/jruby/RubyKernel.java:954
           require at /home/jiii/.rvm/rubies/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
  require_relative at file:/home/jiii/.rvm/rubies/jruby-9.0.0.0.pre1/lib/jruby.jar!/jruby/kernel/kernel.rb:24
            (root) at /home/jiii/.rvm/gems/jruby-9.0.0.0.pre1/gems/jruby_art-0.4.2/lib/jruby_art/runners/base.rb:7
           require at org/jruby/RubyKernel.java:954
            (root) at /home/jiii/.rvm/rubies/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
           require at /home/jiii/.rvm/rubies/jruby-9.0.0.0.pre1/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
        __script__ at /home/jiii/.rvm/gems/jruby-9.0.0.0.pre1/gems/jruby_art-0.4.2/lib/jruby_art/runners/run.rb:1


jruby -v
jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [linux-amd64]

```

I have Processing 3.0b3,  I tried with the one distributed on the website, and a custom build. Same error. 
My version of JRuby is  this from RVM : 
> jruby-9.0.0.0.pre1 [ x86_64 ]

Cheers, 

Jeremy.

**Comment by monkstone** [comment]
jruby-9.0.0.0.pre1 is broken use jruby-9.0.0.0 release or use --nojruby flag to use jruby-complete-9.0.0.0 also make sure you are using JWishy for JRubyArt preferably version-0.6

**Comment by poqudrof** [comment]
I found a solution here to update to jruby 9000 with RVM. 

http://www.randomactsofsentience.com/2015/07/rvm-install-jruby-9000-insists-on.html

But I think my mistake was due to the config file, I filled up ~./jruby_art/config.yaml  instead of yml ...
